"""Mock Salesforce REST API.

Serves synthetic sObject records generated by `fanuni.generator` from a data
directory (FANUNI_SF_DATA_DIR). Faithful enough for a real extractor to be
written against it: OAuth client-credentials token exchange, a restricted SOQL
query endpoint with SystemModstamp watermark filtering, and cursor pagination
via nextRecordsUrl. Field projection is not implemented — records are returned
whole regardless of the SELECT list.

Imports only fastapi/pydantic/stdlib so the service image stays small — keep
pipeline dependencies out of this module.
"""

from __future__ import annotations

import base64
import binascii
import json
import os
import re
from pathlib import Path
from typing import Annotated, Any

from fastapi import FastAPI, Form, Header, HTTPException, Query

API_VERSION = "v59.0"
PAGE_SIZE = 200

app = FastAPI(title="fanuni mock Salesforce API", docs_url=None, redoc_url=None)


def data_dir() -> Path:
    return Path(os.environ.get("FANUNI_SF_DATA_DIR", "data/sfmock"))


def expected_token() -> str:
    return os.environ.get("FANUNI_SF_TOKEN", "dev-local-token")


_SOBJECT_FILES = {"Contact": "contacts.jsonl", "Opportunity": "opportunities.jsonl"}


def _load_sobject(sobject: str) -> list[dict[str, Any]]:
    path = data_dir() / _SOBJECT_FILES[sobject]
    if not path.is_file():
        raise HTTPException(status_code=404, detail=f"no data for sObject {sobject}")
    with path.open(encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


@app.get("/healthz")
def healthz() -> dict[str, object]:
    return {"status": "ok", "data_dir_present": data_dir().is_dir()}


@app.post("/services/oauth2/token")
def token(
    grant_type: Annotated[str, Form()],
    client_id: Annotated[str, Form()],
    client_secret: Annotated[str, Form()],
) -> dict[str, str]:
    if grant_type != "client_credentials":
        raise HTTPException(status_code=400, detail="unsupported_grant_type")
    if client_id != os.environ.get(
        "FANUNI_SF_CLIENT_ID", "fanuni-dev-client"
    ) or client_secret != os.environ.get("FANUNI_SF_CLIENT_SECRET", "dev-client-secret"):
        raise HTTPException(status_code=401, detail="invalid_client")
    return {"access_token": expected_token(), "token_type": "Bearer"}


def _require_auth(authorization: str | None) -> None:
    if authorization != f"Bearer {expected_token()}":
        raise HTTPException(status_code=401, detail="INVALID_SESSION_ID")


_SOQL = re.compile(
    r"^\s*SELECT\s+.+?\s+FROM\s+(?P<sobject>Contact|Opportunity)"
    r"(?:\s+WHERE\s+SystemModstamp\s*>\s*(?P<after>[\dT:.+Z-]+))?"
    r"(?:\s+ORDER\s+BY\s+SystemModstamp(?:\s+ASC)?)?"
    r"(?:\s+LIMIT\s+(?P<limit>\d+))?\s*$",
    re.IGNORECASE,
)


def _query_page(sobject: str, after: str | None, offset: int, limit: int | None) -> dict[str, Any]:
    records = _load_sobject(sobject)
    if after:
        records = [r for r in records if str(r.get("SystemModstamp", "")) > after]
    records.sort(key=lambda r: (str(r.get("SystemModstamp", "")), str(r.get("Id", ""))))
    if limit is not None:
        records = records[:limit]

    total = len(records)
    page = records[offset : offset + PAGE_SIZE]
    for record in page:
        record.setdefault(
            "attributes",
            {"type": sobject, "url": f"/services/data/{API_VERSION}/sobjects/{sobject}"},
        )
    done = offset + PAGE_SIZE >= total
    body: dict[str, Any] = {"totalSize": total, "done": done, "records": page}
    if not done:
        cursor = base64.urlsafe_b64encode(
            json.dumps(
                {"sobject": sobject, "after": after, "offset": offset + PAGE_SIZE, "limit": limit}
            ).encode()
        ).decode()
        body["nextRecordsUrl"] = f"/services/data/{API_VERSION}/query/{cursor}"
    return body


@app.get(f"/services/data/{API_VERSION}/query")
def query(
    q: Annotated[str, Query()],
    authorization: Annotated[str | None, Header()] = None,
) -> dict[str, Any]:
    _require_auth(authorization)
    match = _SOQL.match(q)
    if not match:
        raise HTTPException(status_code=400, detail=f"MALFORMED_QUERY: {q}")
    limit = match.group("limit")
    return _query_page(
        match.group("sobject").capitalize(),
        match.group("after"),
        offset=0,
        limit=int(limit) if limit else None,
    )


@app.get(f"/services/data/{API_VERSION}/query/{{cursor}}")
def query_next(
    cursor: str,
    authorization: Annotated[str | None, Header()] = None,
) -> dict[str, Any]:
    _require_auth(authorization)
    try:
        state = json.loads(base64.urlsafe_b64decode(cursor.encode()))
    except (binascii.Error, ValueError) as exc:
        raise HTTPException(status_code=400, detail="INVALID_QUERY_LOCATOR") from exc
    return _query_page(state["sobject"], state["after"], state["offset"], state["limit"])
